global_defaults = {'template_image': None,
                   'ra': None,
                   'dec': None,
                   'rotation': 0.0,
                   'pixel_fraction': 1.0,
                   'clean': True,
                   'num_cores': 8,
                   'sky_subtract': True,
                   'use_tweakshifts': True
                   }

instrument_defaults = {'wfc3_uvis': {'env_ref': 'iref',
                                     'group': '',
                                     'driz_bits': 0,
                                     'nchip': 2,
                                     'nx': 5200,
                                     'ny': 5200,
                                     'pix_scale': 0.04,
                                     'input_files': '*_flc.fits',
                                     'crpars': {'rdnoise': 6.5,
                                                'gain': 1.0,
                                                'saturation': 70000.0,
                                                'sig_clip': 4.0,
                                                'sig_frac': 0.2,
                                                'obj_lim': 6.0}
                                     },
                       'wfc3_uvis_sub': {'env_ref': 'iref',
                                         'group': '',
                                         'driz_bits': 0,
                                         'nchip': 1,
                                         'nx': 1400,
                                         'ny': 1400,
                                         'pix_scale': 0.04,
                                         'input_files': '*_flt.fits',
                                         'crpars': {'rdnoise': 6.5,
                                                    'gain': 1.0,
                                                    'saturation': 70000.0,
                                                    'sig_clip': 4.0,
                                                    'sig_frac': 0.2,
                                                    'obj_lim': 6.0}
                                         },
                       'acs': {'env_ref': 'jref',
                               'group': '',
                               'driz_bits': 0,
                               'nchip': 2,
                               'nx': 5200,
                               'ny': 5200,
                               'pix_scale': 0.05,
                               'input_files': '*_flc.fits',
                               'crpars': {'rdnoise': 6.5,
                                          'gain': 1.0,
                                          'saturation': 70000.0,
                                          'sig_clip': 3.0,
                                          'sig_frac': 0.1,
                                          'obj_lim': 5.0}
                               },
                       'acs_sub': {'env_ref': 'jref',
                                   'group': '',
                                   'driz_bits': 0,
                                   'nchip': 1,
                                   'nx': 1400,
                                   'ny': 1400,
                                   'pix_scale': 0.05,
                                   'input_files': '*_flt.fits',
                                   'crpars': {'rdnoise': 6.5,
                                              'gain': 1.0,
                                              'saturation': 70000.0,
                                              'sig_clip': 3.0,
                                              'sig_frac': 0.1,
                                              'obj_lim': 5.0}
                                   },
                       'acs_hrc': {'env_ref': 'jref',
                                   'group': '',
                                   'driz_bits': 0,
                                   'nchip': 1,
                                   'nx': 1400,
                                   'ny': 1400,
                                   'pix_scale': 0.025,
                                   'input_files': '*_flt.fits',
                                   'crpars': {'rdnoise': 6.5,
                                              'gain': 1.0,
                                              'saturation': 155000.0,
                                              'sig_clip': 3.0,
                                              'sig_frac': 0.1,
                                              'obj_lim': 5.0}
                                   },
                       'wfc3_ir': {'env_ref': 'iref',
                                   'group': '',
                                   'driz_bits': 512,
                                   'nchip': 1,
                                   'nx': 1700,
                                   'ny': 1700,
                                   'pix_scale': 0.09,
                                   'input_files': '*_flt.fits',
                                   # Note that wfc3_ir does not ever do cosmic ray removal
                                   # because it automatically flags cosmic rays using up the ramp
                                   # sampling
                                   },
                       'stis': {'env_ref': 'oref',
                                'group': '',
                                'driz_bits': 0,
                                'nchip': 1,
                                'nx': 1400,
                                'ny': 1400,
                                'pix_scale': 0.05,
                                'input_files': '*_flt.fits',
                                'crpars': {'rdnoise': 6.5,
                                           'gain': 1.0,
                                           'saturation': 30000.0,
                                           'sig_clip': 3.0,
                                           'sig_frac': 0.1,
                                           'obj_lim': 5.0}
                                },
                       'wfpc2_pc': {'env_ref': 'uref',
                                    'group': '1',
                                    'driz_bits': 0,
                                    'nchip': 1,
                                    'nx': 1000,
                                    'ny': 1000,
                                    'pix_scale': 0.046,
                                    'input_files': '*_c0m.fits',
                                    'crpars': {'rdnoise': 10.0,
                                               'gain': 7.0,
                                               'saturation': 27000.0,
                                               'sig_clip': 4.0,
                                               'sig_frac': 0.3,
                                               'obj_lim': 6.0}
                                    },
                       'wfpc2_all': {'env_ref': 'uref',
                                     'group': '',
                                     'driz_bits': 0,
                                     'nchip': 4,
                                     'nx': 5200,
                                     'ny': 5200,
                                     'pix_scale': 0.046,
                                     'input_files': '*_c0m.fits',
                                     'crpars': {'rdnoise': 10.0,
                                                'gain': 7.0,
                                                'saturation': 27000.0,
                                                'sig_clip': 4.0,
                                                'sig_frac': 0.3,
                                                'obj_lim': 6.0}
                                     },
                       'wfpc2_wf': {'env_ref': 'uref',
                                    'group': '',
                                    'driz_bits': 0,
                                    'nchip': 4,
                                    'nx': 2400,
                                    'ny': 2400,
                                    'pix_scale': 0.0996,
                                    'input_files': '*_c0m.fits',
                                    'crpars': {'rdnoise': 10.0,
                                               'gain': 7.0,
                                               'saturation': 27000.0,
                                               'sig_clip': 4.0,
                                               'sig_frac': 0.3,
                                               'obj_lim': 6.0}
                                    }
                       }


def get_drizzle_parameters(instrument, options):

    for key in global_defaults.keys():
        if key not in options.keys():
            options[key] = global_defaults[key]

    for key in instrument_defaults[instrument].keys():
        if key not in options.keys():
            options[key] = instrument_defaults[instrument][key]

    return options
